{{ if eq .Values.config.sensor.createSecret true}}
apiVersion: v1
kind: Secret
data:
  ca.pem: |
{{ .Files.Get "secrets/ca.pem" | b64enc | indent 4 }}
  sensor-cert.pem: |
{{ .Files.Get "secrets/sensor-cert.pem" | b64enc | indent 4 }}
  sensor-key.pem: |
{{ .Files.Get "secrets/sensor-key.pem" | b64enc | indent 4 }}
metadata:
  labels:
    auto-upgrade.stackrox.io/component: sensor
  name: sensor-tls
  namespace: stackrox
type: Opaque
{{ end }}
